# Generated by Django 5.1.3 on 2024-12-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main Course', 'Main Course'), ('Soup', 'Soup'), ('Dessert', 'Dessert')], max_length=50, verbose_name='Menu Type'),
        ),
    ]
